### ISSUE TITLE
Goalpost 3: Make Browser Compatible

### ISSUE THREAD

**Issue by coolaj86** [dashhive/dashhd-cli#2]
- [x] Convert to BigInt
- [x] Convert to Uint8Array
- [x] DataView ??
- [x] Convert to Noble Secp256k1 + TweakUtil (in tests)
- [x] #4
- [x] #5

**Comment by coolaj86** [comment]
Will need a Private Key Tweak / Add function: https://github.com/paulmillr/noble-secp256k1/issues/73

**Comment by coolaj86** [comment]
This has been done in what is now <https://github.com/dashhive/DashHD.js>.

**Comment by riongull** [comment]
@coolaj86,there are unchecked boxes above. Are they done as well?  Let's check them off if so.

**Comment by coolaj86** [comment]
@riongull the responsibility of what goes where shifted, but it's all handled appropriately regardless.

I checked the boxes, but they don't mean the same thing anymore.
